services:
  - type: web
    name: quizverse
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn --workers 1 --threads 2 --timeout 45 --bind :$PORT app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: quizverse-db
          property: connectionString
    healthCheckPath: /healthcheck
databases:
  - name: quizverse-db
    postgresVersion: 16
