services:
  - type: web
    name: quizverse-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quizverse
          property: connectionString
      - key: SECRET_KEY
        value: super_secret_123
      - key: ADMIN_PASSWORD
        value: Quizverse@712503
